name: CI
on:
  workflow_dispatch:
  pull_request:

  # triggering CI default branch improves caching
  # see https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
  push:
    branches:
      - main
      - mbarton/docker-build-sep-25

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: guardian/setup-scala@v1
      - name: Run CI script
        env:
          AZURE_REGISTRY_NAME: ${{ secrets.AZURE_REGISTRY_NAME }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_LIVE_APP_NAME: ${{ secrets.AZURE_LIVE_APP_NAME }}
        run: s/ci
      # - name: Test Summary
      #   uses: test-summary/action@v2
      #   if: always()
      #   with:
      #     paths: "test-results/**/TEST-*.xml"
